### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by sindresorhus**
Tests were failing before this PR.

-

@SBoudrias Can you publish a new version of this package when merged?

### CODE REVIEW

**Comment by SBoudrias** [comment]
Will have to fix the failure before a release, but I'll try to come over it.

BTW, I intend to remove this module from yeoman-generator 0.19.0

**Comment by sindresorhus** [comment]
> BTW, I intend to remove this module from yeoman-generator 0.19.0

Awesome! Much better for people to require it directly :)

**Comment by sindresorhus** [comment]
@SBoudrias Can you publish a new version?

**Comment by SBoudrias** [comment]
Done!

**Pull request merged**
